# Generated by Django 4.0.5 on 2022-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='proportions',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_desc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
